Importing Dependencies

In [348]:
import numpy as np

In [349]:
# consider two points with 2 dimensions
p1 = (1,1)
p2 = (2,2)

In [350]:
# calculate Euclidean Distance
dist = (p1[0] - p2[0])**2 + (p1[1] - p2[1])**2
euclidean_dist = np.sqrt(dist)
print(euclidean_dist)

1.4142135623730951


In [351]:
# consider two points with 2 dimensions
p1 = (1,1,1)
p2 = (2,2,2)

# calculate Euclidean Distance
dist = (p1[0] - p2[0])**2 + (p1[1] - p2[1])**2 + (p1[2] - p2[2])**2
euclidean_dist = np.sqrt(dist)
print(euclidean_dist)

1.7320508075688772


In [352]:
# consider two points with 2 dimensions
p1 = (1,1,1,1)
p2 = (2,2,2,2)

dist = 0
for i in range(len(p1)):
  dist = dist + (p1[i] - p2[i])**2

euclidean_dist = np.sqrt(dist)
print(euclidean_dist)

2.0


Create Function for calculating Euclidean Distance

In [353]:
def get_euclidean_distance(p1,p2):
  dist = 0
  for i in range(len(p1)):
    dist = dist + (p1[i] - p2[i])**2

euclidean_dist = np.sqrt(dist)
print(euclidean_dist)

2.0


In [354]:
get_euclidean_distance((1,1,1,1),(2,2,2,2))

In [355]:
get_euclidean_distance((1,1,1),(2,2,2))

Manhattan Distance

In [356]:
def get_manhattan_distance(p1,p2):
  dist = 0
  for i in range(len(p1)):
    dist = dist + abs(p1[i] - p2[i])
    manhattan_dist = dist
  print(manhattan_dist)

In [357]:
get_manhattan_distance((1,1,1,1),(2,2,2,2))

4


In [358]:
# distance b/w 2 similar datapoints
print(get_euclidean_distance((63,1,3,145,233,1,0,150,0,2.3,0,0,1),(37,1,2,130,250,0,1,187,0,3.5,0,0,2)))
print(get_manhattan_distance((63,1,3,145,233,1,0,150,0,2.3,0,0,1),(37,1,2,130,250,0,1,187,0,3.5,0,0,2)))

None
100.2
None


In [359]:
# distance b/w 2 dissimilar datapoints

print(get_euclidean_distance((63,1,3,145,233,1,0,150,0,2.3,0,0,1),(67,1,0,160,286,0,0,108,1,1.5,1,3,2)))
print(get_manhattan_distance((63,1,3,145,233,1,0,150,0,2.3,0,0,1),(67,1,0,160,286,0,0,108,1,1.5,1,3,2)))

None
124.8
None


In [360]:
import numpy as np
import statistics

K Nearest Neighbors Classifier

In [361]:
class KNN_Classifier():
  def __init__(self, distance_metric):
    self.distance_metric = distance_metric

  def get_distance_metric(self,training_data_point, test_data_point):
    if(self.distance_metric == 'euclidean'):
      dist = 0
      for i in range(len(training_data_point)-1):
        dist = dist + (training_data_point[i] - test_data_point[i])**2

      euclidean_dist = np.sqrt(dist)
      return euclidean_dist

    elif (self.distance_metric == 'manhattan'):
      dist = 0
      for i in range(len(training_data_point)-1):
        dist = dist + (training_data_point[i] - test_data_point[i])**2

      manhattan_dist = dist
      return manhattan_dist

  def nearest_neighbors(self, X_train, test_data, k):
    distance_list = []
    for training_data in X_train:
      distance = self.get_distance_metric(training_data, test_data)
      distance_list.append((training_data, distance))

    distance_list.sort(key=lambda x:x[1])

    neighbors_list = []
    for j in range(k):
      neighbors_list.append(distance_list[j][0])
    return neighbors_list

  def predict(self, X_train, test_data, k):
    neighbors = self.nearest_neighbors(X_train, test_data, k)
    for data in neighbors:
      label = []
      label.append(data[-1])

    predicted_class = statistics.mode(label)
    return predicted_class

In [362]:
classifier = KNN_Classifier(distance_metric='euclidean')

In [363]:
classifier = KNN_Classifier(distance_metric='manhattan')

In [364]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [365]:
diabetes = pd.read_csv("/content/diabetes.csv")

In [366]:
diabetes.head()

Index  Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0    0.0            6      148             72             35        0  33.6   
1    1.0            1       85             66             29        0  26.6   
2    2.0            8      183             64              0        0  23.3   
3    3.0            1       89             66             23       94  28.1   
4    4.0            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  Outcome.1  
0                     0.627   50        1        1.0  
1                     0.351   31        0       -1.0  
2                     0.672   32        1        1.0  
3                     0.167   21        0       -1.0  
4                     2.288   33        1        1.0

In [367]:
diabetes.shape

(768, 11)

In [368]:
X = diabetes.drop(columns = ["Index", "Outcome", "Outcome.1"], axis = 1)
Y = diabetes['Outcome']

In [369]:
X = X.to_numpy()
Y = Y.to_numpy()

In [370]:
print(X)
print(Y)

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]
[1 0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0
 1 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1
 1 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0
 1 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 1
 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0
 1 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 1 1 1 0 0
 1 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1 0

In [371]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)
print(X.shape, X_train.shape, X_test.shape)

(768, 8) (614, 8) (154, 8)


In [372]:
X_train_8_features = X_train
X_train = np.insert(X_train, 8, Y_train, axis=1)
print(X_train)

[[0.00e+00 1.19e+02 0.00e+00 ... 1.41e-01 2.40e+01 1.00e+00]
 [6.00e+00 1.05e+02 7.00e+01 ... 1.22e-01 3.70e+01 0.00e+00]
 [1.00e+00 1.89e+02 6.00e+01 ... 3.98e-01 5.90e+01 1.00e+00]
 ...
 [1.10e+01 8.50e+01 7.40e+01 ... 3.00e-01 3.50e+01 0.00e+00]
 [4.00e+00 1.12e+02 7.80e+01 ... 2.36e-01 3.80e+01 0.00e+00]
 [0.00e+00 8.60e+01 6.80e+01 ... 2.38e-01 2.50e+01 0.00e+00]]


In [373]:
X_train.shape

(614, 9)

In [374]:
print(X_train[:,8])

[1. 0. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0.
 0. 1. 1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1.
 0. 0. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1.
 0. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0.
 0. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1. 0.
 0. 0. 0. 1. 0. 1. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0.
 0. 1. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0.
 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 0.
 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0.

Model: KNN classifier

In [375]:
classifier = KNN_Classifier(distance_metric = 'euclidean')

Note: KNN can predict lable for only one datapoint at a time

In [376]:
prediction = classifier.predict(X_train, X_test[0], k=5)

In [377]:
print(X_test[0])

[  3.    106.     72.      0.      0.     25.8     0.207  27.   ]


In [378]:
print(Y_test[0])

0


In [379]:
print(prediction)

0.0


In [380]:
prediction = classifier.predict(X_train, X_test[1], k=5)

In [381]:
print(X_test[0])

[  3.    106.     72.      0.      0.     25.8     0.207  27.   ]


In [382]:
print(Y_test[0])

0


In [383]:
print(prediction)

1.0


In [384]:
prediction = classifier.predict(X_train, X_test[2], k=5)

In [385]:
print(X_test[0])

[  3.    106.     72.      0.      0.     25.8     0.207  27.   ]


In [386]:
print(Y_test[0])

0


In [387]:
print(prediction)

0.0


In [388]:
X_test.shape

(154, 8)

In [389]:
X_test_size = X_test.shape[0]
print(X_test_size)

154


In [390]:
y_pred = []
for i in range(X_test_size):
  prediction = classifier.predict(X_train, X_test[i], k=5)
  y_pred.append(prediction)

In [391]:
print(y_pred)

[0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0]


In [392]:
y_true = Y_test

Model Evaluation

In [393]:
acc = accuracy_score(y_true, y_pred)

In [394]:
print(acc*100)

69.48051948051948


KNN in Sklearn

In [395]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(p=2)

In [396]:
classifier.fit(X_train_8_features, Y_train)

KNeighborsClassifier()

Model Evaluation

In [397]:
print(X_train.shape[1])  # Number of features in training data
print(X_test.shape[1])   # Number of features in test data


9
8


In [398]:
y_pred = classifier.predict(X_test)

In [399]:
acc = accuracy_score(Y_test, y_pred)

In [400]:
print(acc*100)

72.72727272727273


In [401]:
y_true = Y_test

Model Evaluation

In [402]:
acc = accuracy_score(Y_test, y_pred)

In [403]:
print(acc*100)

72.72727272727273


In [404]:
classifier = KNeighborsClassifier(p=1)

In [405]:
classifier.fit(X_train_8_features, Y_train)

KNeighborsClassifier(p=1)

In [406]:
y_pred = classifier.predict(X_test)

In [407]:
acc = accuracy_score(Y_test, y_pred)

In [408]:
print(acc*100)

77.92207792207793
