Importing Dependencies

In [195]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error


In [196]:
# consider two points with 2 dimensions
p1 = (1,1)
p2 = (2,2)

In [197]:
# calculate Euclidean Distance
dist = (p1[0] - p2[0])**2 + (p1[1] - p2[1])**2
euclidean_dist = np.sqrt(dist)
print(euclidean_dist)

1.4142135623730951


In [198]:
# consider two points with 3 dimensions
p1 = (1,1,1)
p2 = (2,2,2)

# calculate Euclidean Distance
dist = (p1[0] - p2[0])**2 + (p1[1] - p2[1])**2 + (p1[2] - p2[2])**2
euclidean_dist = np.sqrt(dist)
print(euclidean_dist)

1.7320508075688772


In [199]:
# consider two points with 4 dimensions
p1 = (1,1,1,1)
p2 = (2,2,2,2)

dist = 0
for i in range(len(p1)):
  dist = dist + (p1[i] - p2[i])**2

euclidean_dist = np.sqrt(dist)
print(euclidean_dist)

2.0


Create Function for calculating Euclidean Distance

In [200]:
def get_euclidean_distance(p1,p2):
  dist = 0
  for i in range(len(p1)):
    dist = dist + (p1[i] - p2[i])**2

euclidean_dist = np.sqrt(dist)
print(euclidean_dist)

2.0


In [201]:
get_euclidean_distance((1,1,1,1),(2,2,2,2))

In [202]:
get_euclidean_distance((1,1,1),(2,2,2))

Manhattan Distance

In [203]:
def get_manhattan_distance(p1,p2):
  dist = 0
  for i in range(len(p1)):
    dist = dist + abs(p1[i] - p2[i])
    manhattan_dist = dist
  print(manhattan_dist)

In [204]:
get_manhattan_distance((1,1,1,1),(2,2,2,2))

4


In [205]:
# distance b/w 2 similar datapoints
print(get_euclidean_distance((63,1,3,145,233,1,0,150,0,2.3,0,0,1),(37,1,2,130,250,0,1,187,0,3.5,0,0,2)))
print(get_manhattan_distance((63,1,3,145,233,1,0,150,0,2.3,0,0,1),(37,1,2,130,250,0,1,187,0,3.5,0,0,2)))

None
100.2
None


In [206]:
# distance b/w 2 dissimilar datapoints

print(get_euclidean_distance((63,1,3,145,233,1,0,150,0,2.3,0,0,1),(67,1,0,160,286,0,0,108,1,1.5,1,3,2)))
print(get_manhattan_distance((63,1,3,145,233,1,0,150,0,2.3,0,0,1),(67,1,0,160,286,0,0,108,1,1.5,1,3,2)))

None
124.8
None


In [207]:
import numpy as np
import statistics

K Nearest Neighbors Regression

In [208]:
class KNN_Regression():
  def __init__(self, distance_metric):
    self.distance_metric = distance_metric

  def get_distance_metric(self,training_data_point, test_data_point):
    if(self.distance_metric == 'euclidean'):
      dist = 0
      for i in range(len(training_data_point)-1):
        dist = dist + (training_data_point[i] - test_data_point[i])**2

      euclidean_dist = np.sqrt(dist)
      return euclidean_dist

    elif (self.distance_metric == 'manhattan'):
      dist = 0
      for i in range(len(training_data_point)-1):
        dist = dist + (training_data_point[i] - test_data_point[i])**2

      manhattan_dist = dist
      return manhattan_dist

  def nearest_neighbors(self, X_train, test_data, k):
    distance_list = []
    for training_data in X_train:
      distance = self.get_distance_metric(training_data, test_data)
      distance_list.append((training_data, distance))

    distance_list.sort(key=lambda x:x[1])

    neighbors_list = []
    for j in range(k):
      neighbors_list.append(distance_list[j][0])
    return neighbors_list

  def predict(self, X_train, test_data, k):
    neighbors = self.nearest_neighbors(X_train, test_data, k)
    for data in neighbors:
      label = []
      label.append(data[-1])

    predicted_class = statistics.mode(label)
    return predicted_class

In [209]:
regressor = KNN_Regression(distance_metric='euclidean')

In [210]:
regressor = KNN_Regression(distance_metric='manhattan')

In [211]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [212]:
Bhouse = pd.read_csv("/content/BostonHousing.csv")

In [213]:
Bhouse.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [214]:
Bhouse.shape

(506, 14)

In [215]:
X = Bhouse.drop(columns = ["medv"], axis = 1)
Y = Bhouse["medv"]

In [216]:
X = X.to_numpy()
Y = Y.to_numpy()

In [217]:
print("This is X:",X)
print("This is Y:",Y)

This is X: [[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
This is Y: [24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 1

In [218]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=2)
print(X.shape, X_train.shape, X_test.shape)

(506, 13) (404, 13) (102, 13)


In [219]:
X_train_13_features = X_train
X_train = np.insert(X_train, 13, Y_train, axis=1)
print(X_train)

[[1.8159e-01 0.0000e+00 7.3800e+00 ... 3.9690e+02 6.8700e+00 2.3100e+01]
 [8.0140e-02 0.0000e+00 5.9600e+00 ... 3.9690e+02 8.7700e+00 2.1000e+01]
 [1.9650e-02 8.0000e+01 1.7600e+00 ... 3.4160e+02 1.2930e+01 2.0100e+01]
 ...
 [1.7331e-01 0.0000e+00 9.6900e+00 ... 3.9690e+02 1.2010e+01 2.1800e+01]
 [6.2739e-01 0.0000e+00 8.1400e+00 ... 3.9562e+02 8.4700e+00 1.9900e+01]
 [2.3004e+00 0.0000e+00 1.9580e+01 ... 2.9709e+02 1.1100e+01 2.3800e+01]]


In [220]:
X_train.shape

(404, 14)

In [221]:
print(X_train[:,13])

[23.1 21.  20.1 34.7 13.9 13.5 22.  15.2 10.9 22.7 13.8  5.6 29.8 50.
 34.9 20.6 23.4 19.2 32.7 19.6 27.   8.4 46.  21.7 27.1 19.4 19.3 24.8
 22.6 31.7 18.5  8.7 17.4 23.7 13.3 10.5 12.7 25.  19.7 14.9 24.2 25.
 14.9 17.  15.6 12.7 24.5 15.  50.  17.5 21.2 32.  15.6 22.9 19.3 18.7
 23.3 37.2 30.1 33.1 21.  50.  13.4  5.  16.5  8.4 28.7 19.5 20.6 45.4
 39.8 33.4 19.8 33.4 25.3 50.  12.5 17.4 18.6 22.6 50.  23.8 23.3 23.1
 41.7 16.1 31.6 36.1  7.  20.4 20.  12.  25.  50.  37.9 23.1 41.3 17.6
 16.3 30.1 22.9 19.8 17.1 18.9 18.9 22.6 23.2 33.2 15.  11.7 18.8 20.8
 18.  19.6 50.  17.2 16.4 17.5 14.6 33.1 14.5 43.8 34.9 20.4 14.6  8.1
 11.8 11.8 18.7  6.3 24.  13.1 19.6 50.  22.3 18.9 31.2 20.7 32.2 36.2
 14.2 15.7 50.  20.4 16.2 13.4 50.  31.6 12.3 19.2 29.8 31.5 22.8 10.2
 24.1 23.7 22.  13.8 28.4 33.2 13.1 19.  26.6 37.  30.8 22.8 10.2 22.2
 24.5 36.2 23.1 20.1 19.5 10.8 22.7 19.5 20.1  9.6 42.8 48.8 13.1 20.3
 24.8 14.1 21.7 22.2 33.  21.1 25.  19.1 32.4 13.6 15.1 23.1 27.5 19.4
 26.5 27

Model: KNN regression

In [222]:
regressor = KNN_Regression(distance_metric = 'euclidean')

Note: KNN can predict lable for only one datapoint at a time

In [223]:
prediction = regressor.predict(X_train, X_test[0], k=5)

In [224]:
print(X_test[0])

[  5.82115   0.       18.1       0.        0.713     6.513    89.9
   2.8016   24.      666.       20.2     393.82     10.29   ]


In [225]:
print(Y_test[0])

20.2


In [226]:
print(prediction)

19.9


In [227]:
prediction = regressor.predict(X_train, X_test[1], k=5)

In [228]:
print(X_test[0])

[  5.82115   0.       18.1       0.        0.713     6.513    89.9
   2.8016   24.      666.       20.2     393.82     10.29   ]


In [229]:
print(Y_test[0])

20.2


In [230]:
print(prediction)

24.3


In [231]:
prediction = regressor.predict(X_train, X_test[2], k=5)

In [232]:
print(X_test[0])

[  5.82115   0.       18.1       0.        0.713     6.513    89.9
   2.8016   24.      666.       20.2     393.82     10.29   ]


In [233]:
print(Y_test[0])

20.2


In [234]:
print(prediction)

31.6


In [235]:
X_test.shape

(102, 13)

In [236]:
X_test_size = X_test.shape[0]
print(X_test_size)

102


In [237]:
y_pred = []
for i in range(X_test_size):
  prediction = regressor.predict(X_train, X_test[i], k=5)
  y_pred.append(prediction)

In [238]:
print(y_pred)

[19.9, 24.3, 31.6, 29.6, 16.4, 16.2, 24.0, 26.2, 9.6, 24.3, 21.7, 23.3, 24.3, 28.4, 15.2, 26.6, 17.8, 12.3, 11.8, 15.1, 19.0, 19.5, 33.8, 20.0, 13.0, 29.0, 50.0, 18.2, 30.8, 22.2, 17.2, 20.0, 24.5, 20.9, 10.2, 15.6, 14.1, 22.7, 23.1, 21.8, 24.5, 14.5, 18.9, 13.8, 21.2, 12.5, 32.0, 12.5, 33.8, 8.7, 31.5, 31.0, 7.2, 22.2, 21.9, 15.2, 19.5, 26.5, 23.8, 23.1, 24.4, 20.9, 22.6, 45.4, 20.6, 18.3, 31.6, 21.6, 12.5, 23.3, 25.0, 13.8, 28.7, 23.7, 18.2, 23.6, 41.3, 18.2, 42.3, 21.2, 24.5, 19.8, 20.6, 23.4, 30.1, 33.8, 17.8, 22.8, 33.3, 50.0, 24.4, 31.7, 12.7, 50.0, 33.2, 12.7, 23.1, 29.0, 19.9, 17.1, 29.1, 24.4]


In [239]:
y_true = Y_test

Model Evaluation

In [240]:
mean = mean_squared_error(y_true, y_pred)

In [241]:
print(mean)

59.48745098039215


KNN in Sklearn

In [242]:
from sklearn.neighbors import KNeighborsRegressor
regressor = KNeighborsRegressor(p=2)

In [243]:
regressor.fit(X_train_13_features, Y_train)

KNeighborsRegressor()

Model Evaluation

In [244]:
print(X_train.shape[1])  # Number of features in training data
print(X_test.shape[1])   # Number of features in test data


14
13


In [245]:
y_pred = regressor.predict(X_test)

In [246]:
mean = mean_squared_error(Y_test, y_pred)

In [247]:
print(mean)

28.564341176470588


In [248]:
y_true = Y_test

Model Evaluation

In [249]:
mean = mean_squared_error(Y_test, y_pred)

In [250]:
print(mean)

28.564341176470588


In [251]:
regressor = KNeighborsRegressor(p=1)

In [252]:
regressor.fit(X_train_13_features, Y_train)

KNeighborsRegressor(p=1)

In [254]:
y_pred = regressor.predict(X_test)

In [255]:
mean = mean_squared_error(Y_test, y_pred)

In [256]:
print(mean)

22.17821960784314
